#!/usr/bin/env node
/*▄────────▄
  █        █
  █  Ядро  █
  █        █
  ▀────────▀*/
require('./lib/core/core');

/*▄───────▄
  █       █
  █  MVC  █
  █       █
  ▀───────▀*/
// Коллекция текстов
require('./lib/texts/text');

// Коллекция моделей
require('./lib/models/modelFiles');

// Коллекция точек входа
require('./lib/entrypoints/entrypoint');

/*▄──────────────────────────────▄
  █                              █
  █  Список глобальных констант  █
  █                              █
  ▀──────────────────────────────▀*/
$.global = class {
/*┌───────────────┐
  │ Список файлов │
  └───────────────┘*/
    PATH_FILES = {
    //  Откуда копируем    Куда копируем
        'files/start':     'start',
        // 'files/start2':    'start2',
        'files/gitignore': '.gitignore'
    }
};

/*▄───────────────▄
  █               █
  █  Точка входа  █
  █               █
  ▀───────────────▀*/
entrypoint
