#!/usr/bin/env node
/*┌──────┐
  │ Ядро │
  └──────┘*/
require('./lib/core/core');

/*┌─────┐
  │ MVC │
  └─────┘*/
// Точки входа
require('./lib/entrypoints/entrypoint');

/*┌──────────────┐
  │ Список путей │
  └──────────────┘*/
const PATH_FILES = './files'; // Каталог со списком файлов

/*┌───────────────┐
  │ Список файлов │
  └───────────────┘*/
const FILES = [
    ['gitignore', '.gitignore']
];

/*┌─────────────┐
  │ Точка входа │
  └─────────────┘*/
entrypoint
